Proto/ImageQuality/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('image_quality.urls')),
]

Proto/image_quality/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.conf.urls import handler404, handler500


app_name = "image_quality"

urlpatterns = [
    path ('', views.home, name='home'),
    path('personal_info', views.personal_info, name='personal_info'),
    path('ghs_fk', views.ghs_fk, name='ghs_fk'),
    path('profileBuilder', views.profileBuilder, name='profileBuilder'),
    path('rate_recipes',views.rate_recipes, name='rate_recipes'),
    path('choice_evaluation',views.choice_evaluation, name='choice_evaluation'),
    path('thank_u', views.thank_u,name='thank_u'),

]

Proto/image_quality/views.py
from select import select
from django.forms import formset_factory
from django.db.models import Count
# import datetime
from datetime import datetime 
import pandas as pd
from random import choice, sample
import random
from sys import prefix
from django import forms
from django.db import reset_queries
from django.forms.models import ModelForm
from django.http import request
from django.http.request import HttpRequest
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from pandas.core.indexes import category
import itertools
from .forms import Personal_infoForm, recipesRatingForm, Ghs_fkForm, ProfileForm, ChoiceEvaluationForm
from django.db.models import Q

from .models import  Personal_info, recipes, recipesRating, Ghs_fk, Profile, EvaluateChoices
# from .app import *
# Create your views here.
# person_id = 0
import string
import random
import re
from django.core.cache import cache
# Create your views here.


def home(request):
    request.session['person_id'] = 0
    
    # views = ["rate_sate", "rate_paste","rate_snacks","rate_dissert"]
    # shuffle`views`
    # index = 0 // 0-3
    # views[index]
    #prolific_id = , msg)
    #prolific_id = str(prolific_id.group(1))
    full_url = request.get_full_path()
    #request.GET['PROLIFIC_PID']
    # print('Full',request.get_full_path())
    #print(full_url)
    if 'PROLIFIC_PID' in full_url:
        prolific_id = re.search("PROLIFIC_PID=(.*?)&STUDY_ID",full_url)
        request.session['prolific_id'] = str(prolific_id.group(1))
        #print("----------",prolific_id.group(1))
    else:
        request.session['prolific_id'] = '000'
    return render(request, 'image_quality/homes.html')

        # index++
        
def personal_info(request):
    user_selected = Personal_info.objects.filter(id = request.session['person_id'])
    if user_selected:
        Personal_info.objects.filter(id=request.session['person_id']).delete()
    if request.method == 'POST':
        personl_info = Personal_infoForm(request.POST)
        if personl_info.is_valid():
            answer = personl_info.save(commit=False)
            
            rd_str =''.join(random.choice(string.ascii_lowercase) for _ in range(5))
            time_now = datetime.now().strftime('%H%M%S')
            gene_session = 'dars'+time_now +'_'+str(answer.id)+rd_str
            personl_info.instance.session_id = gene_session

            answer = personl_info.save(commit=True)
            
            request.session['person_id'] = answer.id
            gene_session = 'dars'+time_now +'_'+str(answer.id)+rd_str
            personl_info.instance.session_id = request.session['prolific_id']
            
            request.session['session_id'] = gene_session
            answer = personl_info.save(commit=True)
            request.session['n'] = 0

            request.session['person_id'] = answer.id
            # return redirect('image_quality:rate_salad')
            return redirect('image_quality:ghs_fk')
    else:
        personl_info = Personal_infoForm()
    return render(request, 'image_quality/personal_info.html', context={'form': personl_info})


def ghs_fk(request):
    user_selected = Ghs_fk.objects.filter(id = request.session['person_id'])
    if user_selected:
        ghs_fk.objects.filter(id=request.session['person_id']).delete()
    if request.method == 'POST':
        ghs_fk_form = Ghs_fkForm(request.POST)
        #print('------- Here')
        if ghs_fk_form.is_valid():
            answer = ghs_fk_form.save(commit=False)

            rd_str = ''.join(random.choice(string.ascii_lowercase) for _ in range(5))
            time_now = datetime.now().strftime('%H%M%S')
            gene_session = 'dars' +  time_now + '_' + str(answer.id) + rd_str
            ghs_fk_form.instance.session_id = gene_session
            ghs_fk_form.instance.person_id = request.session['person_id']
            #print(';;;;;;;;;;;here')
            answer = ghs_fk_form.save(commit = True)

            #request.session['person_id'] = answer.id
            return redirect('image_quality:profileBuilder')
        else:
            print('not valid')
    else:
        ghs_fk_form = Ghs_fkForm()
    return render(request, 'image_quality/Personal_knowledge.html', context={'form':ghs_fk_form})


def profileBuilder(request):
    user_selected = Profile.objects.filter(person_id = request.session['person_id'])
    if user_selected:
        Profile.objects.filter(person_id=request.session['person_id']).delete()
  
    if request.method == 'POST':
        profile_Form = ProfileForm(request.POST)
        person = request.session['person_id']
        ProfileM = Profile()
        if profile_Form.is_valid():
            # print("-----------here we are")
            # ChoiceEvaltion.person = request.session['person_id']
            profile_ = profile_Form.save(commit=False)
            profile_.person_id = person
            # ChoiceEvaltion.person_id = profile_form.foriengkey
            # profile_.session_id = request.session['prolific_id']
            profile_.save()
            return redirect('image_quality:rate_recipes')
    else:
         profile_Form = ProfileForm()
    return render(request, 'image_quality/ProfileBuilder.html', context={'form': profile_Form})








def rate_recipes(request):
    # print( request.session['n'])
    
    # rated = recipesRating.objects.all().order_by('?')
    # notyetrated = recipes.objects.exclude(id__in = rated)
    # notyetrated_id = recipes.objects.exclude(id__in = rated).values_list('id')
    
    user_selected  = recipesRating.objects.filter(person_id= request.session['person_id'])
    if request.method == "POST":    
        S1 = recipesRatingForm(request.POST, prefix='S1')
        S2 = recipesRatingForm(request.POST,prefix='S2')
        S3 = recipesRatingForm(request.POST,prefix='S3')
        S4 = recipesRatingForm(request.POST,prefix='S4')
        S5 = recipesRatingForm(request.POST,prefix='S5')
        S6 = recipesRatingForm(request.POST,prefix='S6')

        
        S_r1 = recipesRating()
        S_r2 = recipesRating()
        S_r3 = recipesRating()
        S_r4 = recipesRating()
        S_r5 = recipesRating()
        S_r6 = recipesRating()

        
        if S1.is_valid() and S2.is_valid() and S3.is_valid() and S4.is_valid() and  S5.is_valid() and S6.is_valid(): 
            person = Personal_info.objects.get(id=request.session['person_id'])
            
            S_r1.person = S_r2.person =S_r3.person=S_r4.person=S_r5.person= S_r6.person=person
            
            # S = cache.get('S')
            S = request.session['data']
            # print('----',S)

            S_r1.recipes_id = S[0][0]
            S_r1.rating = S1.cleaned_data.get('rating')
            S_r1.judging = S1.cleaned_data.get('judging')
            S_r1.save()
            
            S_r2.recipes_id = S[1][0]
            S_r2.rating = S2.cleaned_data.get('rating')
            S_r2.judging = S2.cleaned_data.get('judging')
            S_r2.save()       
                    
            S_r3.recipes_id = S[2][0]
            S_r3.rating = S3.cleaned_data.get('rating')
            S_r3.judging = S3.cleaned_data.get('judging')    
            S_r3.save()
            
            
            S_r4.recipes_id = S[3][0]
            S_r4.rating = S4.cleaned_data.get('rating')
            S_r4.judging = S4.cleaned_data.get('judging')
            S_r4.save()
                    
            S_r5.recipes_id = S[4][0]
            S_r5.rating = S5.cleaned_data.get('rating')
            S_r5.judging = S5.cleaned_data.get('judging')
            S_r5.save()

            S_r6.recipes_id = S[5][0]
            S_r6.rating = S6.cleaned_data.get('rating')
            S_r6.judging = S6.cleaned_data.get('judging')
            S_r6.save()
            
            # print('#######-N-####',request.session['n'])
            if request.session['n'] == 1:
                return redirect('image_quality:choice_evaluation')
                # user_selected  = recipesRating.objects.filter(person_id= request.session['person_id'])
    
            else :
                request.session['n'] += 1
                return redirect('image_quality:rate_recipes')
                # user_selected  = recipesRating.objects.filter(person_id= request.session['person_id'])
    
        else: 
            print('--------->>not valid')
        
    else:
        
        # for the first 13 user retrive 
        
        # user_selected  = recipesRating.objects.filter(person_id= request.session['person_id']).values_list('person_id')
        # print('-------------->>',user_selected[0][0], request.session['person_id'])
        rated = recipesRating.objects.all()
        if user_selected:
            
            # print('------', user_selected[0][0], request.session['person_id'])
            #person_id = request.session['person_id']
            # rated_recipes = recipes.objects.ex
            # unrated = recipes.objects.exclude(recipes_id = )
             
            # unique_rate = recipesRating.objects.filter(person_id = request.session['person_id'])
            # print('------ uniiiique :',unique_rate,len(unique_rate))
            # notRated =  recipes.objects.exclude(Q(id__in=unique_rate.values('recipes')) | Q(id__in=rated)).values_list("id","Name","image_link").order_by('?')
            
            rated = recipesRating.objects.all().values('recipes')
            print('rated')
            S =  recipes.objects.exclude(id__in=rated)
            
            notRated = S.exclude(id__in = user_selected).values_list("id","Name","image_link").order_by('?')
            
            
            print('not rated by user ',len(notRated))
            S = notRated
            # print("-------",S)
            cache.set('S',S)
            # print(S)
            request.session['data'] = list(S)
            # print(S[0])
            # print('-----',list(S))
            
        else:

Proto/templates/image_quality/Personal_knowledge.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Food Search</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@100&display=swap" rel="stylesheet">
    
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">



    <link rel="shortcut icon" href="{% static 'icon/icon.png'%}">
    <script type="text/javascript">
        /*Scroll to top when arrow up clicked BEGIN*/
        $(window).scroll(function () {
            var height = $(window).scrollTop();
            if (height > 100) {
                $('#back2Top').fadeIn();
            } else {
                $('#back2Top').fadeOut();
            }
        });
        $(document).ready(function () {
            $("#back2Top").click(function (event) {
                event.preventDefault();
                $("html, body").animate({
                    scrollTop: 0
                }, "slow");
                return false;
            });

        });
        /*Scroll to top when arrow up clicked END*/
    </script>



    <style>
        #back2Top {
            width: 40px;
            line-height: 40px;
            overflow: hidden;
            z-index: 999;
            position: fixed;
            cursor: pointer;
            -moz-transform: rotate(270deg);
            -webkit-transform: rotate(270deg);
            -o-transform: rotate(270deg);
            -ms-transform: rotate(270deg);
            transform: rotate(270deg);
            /* position: fixed; */
            bottom: 10px;
            right: 0;
            /* background-image: linear-gradient(-225deg, #B7F8DB 0%, #a1d8e9 100%); */
            color: rgb(61, 57, 57);
            text-align: center;
            font-size: 30px;
            text-decoration: none;
            border-radius: 12px 12px 12px 12px;
        }

        #back2Top:hover {
            background-color: rgb(155, 155, 175);
            color: #000;
        }

        body {
            background-image: linear-gradient(-225deg, #2d2c2abc 0%, #494845 100%);
            /* background: url("{% static 'back/person_info.jpg' %}") no-repeat center center fixed; */
            /* -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover; */
            /* background-image: linear-gradient(to top, #accbee 0%, #e7f0fd 100%); */
            font-family: 'Nunito', sans-serif;
            padding-top: 70px;
            justify-content: center;
            align-items: center;
            text-align: center;
            margin: 0 auto;
            padding-bottom: 30px;
            min-height: 100vh;
        }

        .btn-lg {
            border-color: #ddba59bc !important;
            background: #fbfbfb;
            color: #1f4037;
            /* padding:15px ; */
            margin: auto;
            /* #font-size: 20px; */
            border: 0.10em solid;
            cursor: pointer;
            text-decoration: none;
            font-weight: bold;
            border-radius: 8px 8px 8px 8px;

        }

        .btn-lg:hover {
            background-image: none !important;
            background-color: #ddba59bc !important;
            /* background-image: linear-gradient(-225deg, #c8e9da 0%, #bbd8e0 100%); */
            color: rgb(255, 255, 255);

        }

        .container {
            display: flex;
            flex-direction: column;
            justify-content: left;
            align-items: left;
            max-width: 70%;
            margin: auto;
            border-radius: 12px 12px 12px 12px;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            background: #fbfbfb;
            box-shadow: 1px 2px 8px rgba(0, 0, 0, 0.65);

        }



        .flabel {
            display: flex;
            justify-content: left;
            align-items: left;
            padding: auto;
        }

        .radios {
            font-weight: bold;
            color: rgb(12, 130, 248);
            text-transform: uppercase;
        }

        #rq {
            color: #0eaedf;
        }

        .input {

            height: 15px;
            width: 15px;
            border-radius: 4px;
            cursor: pointer;

        }

        .clabel {
            color: #34495E;
            padding: 0.5rem 0.25rem;
        }

        #error {
            color: #e73b3b;
            font-size: 12px !important;
            text-align: left;
            display: flex;
            justify-content: left;
            align-items: left;
            padding: auto;

        }
    </style>
</head>

<body>
    <div class="container">
        <div>
            <h4 style="font-size: 30px;
        font-weight: 380;
        line-height: 30px;
        font-style: bold; margin-top: 30px;">Food, Health and Cooking</h4>
            <h4 style="font-size: 20px;
        font-weight: 350;
        line-height: 30px;
        font-style: bold; margin-top: 10px;">Presented statements below are  about food , health knowledge and you own cooking skills. Please read each statement carefully and indicate to what extent you agree with each of them.</h4>
        </div>
        <hr style="  border: 0; 
        height: 1px; 
        background-image: linear-gradient(to right, #f0f0f0, #00b9ff, #59d941, #f0f0f0);" />
        <div>
            <form action="" method="POST">

                {% csrf_token %}

                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.FK_9.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.FK_9}}
                    </div>
                </div>
        
        
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.FK_10.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.FK_10}}
                    </div>
                </div>
        
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.FK_11.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.FK_11}}
                    </div>
                </div>
        
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.FK_12.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.FK_12}}
                    </div>
                </div>


        <hr style="  border: 0; 
        height: 1px; 
        background-image: linear-gradient(to right, #f0f0f0, #00b9ff, #59d941, #f0f0f0);" />
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.CS_9.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.CS_9}}
                    </div>
                </div>
        
        
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.CS_10.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.CS_10}}
                    </div>
                </div>
        
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.CS_11.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.CS_11}}
                    </div>
                </div>
        
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.CS_12.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.CS_12}}
                    </div>
                </div>
                <!-- <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.CS_13.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.CS_13}}
                    </div>
                </div> -->
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.CS_13.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.CS_13}}
                    </div>
                </div>
                <div class="flabel" style="padding-top: 15px; margin-bottom:20px;">
                    <p class="col-sm-9 flabel"><b>{{form.CS_14.label}} </b></p>
                    <div style="padding: 6px; font-weight: 500; margin-left: 12px;" class="col-sm">
                        {{form.CS_14}}
                    </div>
                </div>
                <div style="text-align: right; margin-bottom:30px; margin-top:30px;">

                    <button type="submit " name="submit" class="btn-lg col-4"> Next </button>
                </div>
            </form>

            </div>
        <!-- ----------------------------------------------------------- -->
<!------------------------- Next --------------------------->

</div>



        <!-- <hr style="  border: 0; 
            height: 1px; 
            background-image: linear-gradient(to right, #f0f0f0, #00b9ff, #59d941, #f0f0f0);" /> -->

        


    <a id="back2Top" title="Back to top" href="#">&#10148;</a>
    <footer>
        <p class="copyright" style="position:relative;
        color: #e4dcdc;
        bottom: 0;

        "> &#169; DARS RESEARCH GROUP</p>
    </footer>
</body>

</html>

Proto/templates/image_quality/homes.html
{% extends 'image_quality/main.html'%}
{%load static%}
{% block content %}


<div class="header-bar">
    <!-- <div class="row"> -->
    <div class="col-lg-3">
        <img src="{% static 'icon/icon.png'%}" alt="" style=" 
            width: 160px;">
    </div>
    <div>
        <h1>Food Image Attractiveness</h1>
    </div>
    <!-- </div> -->
</div>


<div class="container">

    <h2 style="margin: auto; padding: 20px; text-align: center;">Welcome </h2>



    <p>Welcome to our study! The aim of this study is to gain insights into how individuals make food choices based on the attractiveness of image associated with the food.
        This study is part of the PhD research of Ayoub El Majjodi
        at the University of Bergen, Norway, under supervision of Prof. Dr. Christoph Trattner and Dr. Alain Starke.
        <br>
        Please carefully read the procedure followed in this study to give your informed consent for voluntary
        participation*.
    </p>
    <b>Procedure</b>
    <br>
    <!-- <p>
You will be first asked to answer a few questions about your personal characteristics. Then, you are asked to choose a preferred food category, and to disclose your preferences for recipes in terms of their popularity, serving size, 
cooking time and the number of ingredients.        
<br> -->
Initially, you will be inquired about your personal cooking knowledge. Subsequently, you will be presented with a list of recipe pictures, from four different food categories: dessert, salads, pasta and snacks. Your task is to provide a ratings as to what extent you find the food image attractive and provide justification for your ratings, in total you will rate 12 recipes. Finally you answer 4 question regarding you general ratings and judgment.

    </p>
    <b>Duration</b>
    <p>The study takes around 8-12 minutes to complete. By clicking the <b>'Start'</b>
        button, you agree to have read and understood this consent form.</p>
 

    <div style="text-align: center;">
        <a type="button" value="Start" class="btn-lg" href="{% url 'image_quality:personal_info' %}"> Start </a>
    </div>
    <hr style="  border: 0; 
height: 1px; 
background-image: linear-gradient(to right, #f0f0f0, #00b9ff, #59d941, #f0f0f0);" />
    <p style="font-size: 14px; padding-top: 10px; padding-bottom: 10px; color: black;"> <i
            style="color: red;">*</i> 
            The collected information is used for writing scientific
             publications and is only reported at the group level. Your personal information 
             is processed anonymously and it cannot be traced back to you. 
             For questions about the study, please contact the experimenter, Ayoub El Majjodi: Ayoub.Majjdo@uib.no
    </p>

</div>

{% endblock%}

Proto/templates/image_quality/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Image Quality</title>
    
    <!-- <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@200&display=swap" rel="stylesheet">
     -->

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@100&display=swap" rel="stylesheet">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="shortcut icon" href="{% static 'icon/icon.png'%}">

    <style>
        body {
            background: url("{% static 'back/rcp_ll.jpeg' %}") no-repeat center center fixed;
            -webkit-background-size: cover;
            -moz-background-size: cover;
            -o-background-size: cover;
            background-size: cover;
            font-family: 'Nunito', sans-serif;
            padding-top: 70px;
        }

        .header-bar {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
            color: #fff;
            padding: 20px;
            box-shadow: 1px 2px 8px rgba(0, 0, 0, 0.65);
            border-radius: 8px 8px 0 0;
            /* background: linear-gradient(90deg, #EEA390 0%, #EB796F 43%, #EB796F 100%); */
            /* background: linear-gradient(90deg, rgba(110,181,103,0.9995185574229691) 24%, rgba(39,210,133,1) 44%, rgba(142,217,183,1) 87%); */
            background: #1f4037;
            /* fallback for old browsers */
            background: -webkit-linear-gradient(to right, #99f2c8, #1f4037);
            /* Chrome 10-25, Safari 5.1-6 */
            background: linear-gradient(to right, #ddba59bc, #866e02);
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */

            max-width: 70%;
            height: 150px;
            margin: auto;


        }

        .container {
            box-shadow: 1px 2px 8px rgba(0, 0, 0, 0.65);
            width: 70%;
            margin: auto;
            border-radius: 0 0 8px 8px;
            background-color: #ffff;
            -webkit-box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            box-shadow: 2px 2px 13px -4px rgba(0, 0, 0, 0.21);
            justify-self: center;
            align-items: center;
        }


        h1,
        h2,
        h3 h4,
        h5,
        h6,{
            font-family: 'Releway', sans-serif;
        }

        .btn-lg {
            border-color: #ddba59bc !important;
            background-color: #FFF;
            color: #1f4037;
            padding: 0.3em 4.2em;
            font-size: 20px;
            border: 0.10em solid;
            border-radius: 5px;
            cursor: pointer;
            text-decoration: none;
            font-weight: bold;

        }

        .btn-lg:hover {
            background-image: none !important;
            background-color: #ddba59bc !important;
            color: seashell;

        }
    </style>

</head>

<body>
    {% block content %}

    {% endblock %}
</body>

</html>